// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: proto/hushmesh/workload/v1/workload_attestation.proto

// The mesh's workload attestation service.
//
// Field numbers and types come from the hand-written prost definitions in mesh-process
// actors/actor-spiffe-agent/src/proto.rs. A divergence surfaces at the far end only as an
// undiagnosable status 7, because the mesh answers one uniform refusal for every
// request-derived failure.
//
// Unlike the relay's copy of this file (spire pkg/agent/meshattest/meshattestpb), the INNER
// messages are defined here. The relay has no key for a sealed body and no business parsing
// one; the workload is the end that seals and opens them.

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SealedRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Suite          uint32                 `protobuf:"varint,1,opt,name=suite,proto3" json:"suite,omitempty"`
	RecipientKeyId []byte                 `protobuf:"bytes,2,opt,name=recipient_key_id,json=recipientKeyId,proto3" json:"recipient_key_id,omitempty"`
	// The ML-KEM ciphertext is only half of a hybrid agreement; sender_ecc_public_key_spki carries
	// the other half.
	EncapsulatedKey        []byte `protobuf:"bytes,3,opt,name=encapsulated_key,json=encapsulatedKey,proto3" json:"encapsulated_key,omitempty"`
	Ciphertext             []byte `protobuf:"bytes,4,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	SenderEccPublicKeySpki []byte `protobuf:"bytes,5,opt,name=sender_ecc_public_key_spki,json=senderEccPublicKeySpki,proto3" json:"sender_ecc_public_key_spki,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SealedRequest) Reset() {
	*x = SealedRequest{}
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SealedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealedRequest) ProtoMessage() {}

func (x *SealedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealedRequest.ProtoReflect.Descriptor instead.
func (*SealedRequest) Descriptor() ([]byte, []int) {
	return file_proto_hushmesh_workload_v1_workload_attestation_proto_rawDescGZIP(), []int{0}
}

func (x *SealedRequest) GetSuite() uint32 {
	if x != nil {
		return x.Suite
	}
	return 0
}

func (x *SealedRequest) GetRecipientKeyId() []byte {
	if x != nil {
		return x.RecipientKeyId
	}
	return nil
}

func (x *SealedRequest) GetEncapsulatedKey() []byte {
	if x != nil {
		return x.EncapsulatedKey
	}
	return nil
}

func (x *SealedRequest) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *SealedRequest) GetSenderEccPublicKeySpki() []byte {
	if x != nil {
		return x.SenderEccPublicKeySpki
	}
	return nil
}

type SealedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suite         uint32                 `protobuf:"varint,1,opt,name=suite,proto3" json:"suite,omitempty"`
	Ciphertext    []byte                 `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SealedResponse) Reset() {
	*x = SealedResponse{}
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SealedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealedResponse) ProtoMessage() {}

func (x *SealedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealedResponse.ProtoReflect.Descriptor instead.
func (*SealedResponse) Descriptor() ([]byte, []int) {
	return file_proto_hushmesh_workload_v1_workload_attestation_proto_rawDescGZIP(), []int{1}
}

func (x *SealedResponse) GetSuite() uint32 {
	if x != nil {
		return x.Suite
	}
	return 0
}

func (x *SealedResponse) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type GetEnvelopeKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvelopeKeyRequest) Reset() {
	*x = GetEnvelopeKeyRequest{}
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvelopeKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvelopeKeyRequest) ProtoMessage() {}

func (x *GetEnvelopeKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvelopeKeyRequest.ProtoReflect.Descriptor instead.
func (*GetEnvelopeKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_hushmesh_workload_v1_workload_attestation_proto_rawDescGZIP(), []int{2}
}

type GetEnvelopeKeyResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	KeyId            []byte                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	EccPublicKeySpki []byte                 `protobuf:"bytes,2,opt,name=ecc_public_key_spki,json=eccPublicKeySpki,proto3" json:"ecc_public_key_spki,omitempty"`
	MlkemPublicKey   []byte                 `protobuf:"bytes,3,opt,name=mlkem_public_key,json=mlkemPublicKey,proto3" json:"mlkem_public_key,omitempty"`
	ExpiresAt        int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Leaf first, issuer order after it.
	CertChain [][]byte `protobuf:"bytes,5,rep,name=cert_chain,json=certChain,proto3" json:"cert_chain,omitempty"`
	// ECDSA P-384 over SHA-384, fixed r||s, over a hash chain folded one field at a time in
	// ascending tag order: key_id, ecc_public_key_spki, mlkem_public_key, big-endian expires_at,
	// then trust_domain as UTF-8. The relay never verifies it; the workload does.
	Signature []byte `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	// The entity's own stored trust domain, which the workload compares against the name it
	// dialled. Signed at tag position 7, after the four fields above.
	TrustDomain   string `protobuf:"bytes,7,opt,name=trust_domain,json=trustDomain,proto3" json:"trust_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvelopeKeyResponse) Reset() {
	*x = GetEnvelopeKeyResponse{}
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvelopeKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvelopeKeyResponse) ProtoMessage() {}

func (x *GetEnvelopeKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvelopeKeyResponse.ProtoReflect.Descriptor instead.
func (*GetEnvelopeKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_hushmesh_workload_v1_workload_attestation_proto_rawDescGZIP(), []int{3}
}

func (x *GetEnvelopeKeyResponse) GetKeyId() []byte {
	if x != nil {
		return x.KeyId
	}
	return nil
}

func (x *GetEnvelopeKeyResponse) GetEccPublicKeySpki() []byte {
	if x != nil {
		return x.EccPublicKeySpki
	}
	return nil
}

func (x *GetEnvelopeKeyResponse) GetMlkemPublicKey() []byte {
	if x != nil {
		return x.MlkemPublicKey
	}
	return nil
}

func (x *GetEnvelopeKeyResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *GetEnvelopeKeyResponse) GetCertChain() [][]byte {
	if x != nil {
		return x.CertChain
	}
	return nil
}

func (x *GetEnvelopeKeyResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *GetEnvelopeKeyResponse) GetTrustDomain() string {
	if x != nil {
		return x.TrustDomain
	}
	return ""
}

type AttestationChallengeRequestInner struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AttestationType string                 `protobuf:"bytes,1,opt,name=attestation_type,json=attestationType,proto3" json:"attestation_type,omitempty"`
	ClientRequestId []byte                 `protobuf:"bytes,2,opt,name=client_request_id,json=clientRequestId,proto3" json:"client_request_id,omitempty"`
	ClientTimestamp int64                  `protobuf:"varint,3,opt,name=client_timestamp,json=clientTimestamp,proto3" json:"client_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AttestationChallengeRequestInner) Reset() {
	*x = AttestationChallengeRequestInner{}
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationChallengeRequestInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationChallengeRequestInner) ProtoMessage() {}

func (x *AttestationChallengeRequestInner) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationChallengeRequestInner.ProtoReflect.Descriptor instead.
func (*AttestationChallengeRequestInner) Descriptor() ([]byte, []int) {
	return file_proto_hushmesh_workload_v1_workload_attestation_proto_rawDescGZIP(), []int{4}
}

func (x *AttestationChallengeRequestInner) GetAttestationType() string {
	if x != nil {
		return x.AttestationType
	}
	return ""
}

func (x *AttestationChallengeRequestInner) GetClientRequestId() []byte {
	if x != nil {
		return x.ClientRequestId
	}
	return nil
}

func (x *AttestationChallengeRequestInner) GetClientTimestamp() int64 {
	if x != nil {
		return x.ClientTimestamp
	}
	return 0
}

type AttestationChallengeResponseInner struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ClientRequestId      []byte                 `protobuf:"bytes,1,opt,name=client_request_id,json=clientRequestId,proto3" json:"client_request_id,omitempty"`
	Challenge            []byte                 `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	ChallengeSeed        []byte                 `protobuf:"bytes,3,opt,name=challenge_seed,json=challengeSeed,proto3" json:"challenge_seed,omitempty"`
	PcrNonce             []byte                 `protobuf:"bytes,4,opt,name=pcr_nonce,json=pcrNonce,proto3" json:"pcr_nonce,omitempty"`
	PcrSelectionBitfield uint32                 `protobuf:"varint,5,opt,name=pcr_selection_bitfield,json=pcrSelectionBitfield,proto3" json:"pcr_selection_bitfield,omitempty"`
	ExpiresAt            int64                  `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AttestationChallengeResponseInner) Reset() {
	*x = AttestationChallengeResponseInner{}
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationChallengeResponseInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationChallengeResponseInner) ProtoMessage() {}

func (x *AttestationChallengeResponseInner) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationChallengeResponseInner.ProtoReflect.Descriptor instead.
func (*AttestationChallengeResponseInner) Descriptor() ([]byte, []int) {
	return file_proto_hushmesh_workload_v1_workload_attestation_proto_rawDescGZIP(), []int{5}
}

func (x *AttestationChallengeResponseInner) GetClientRequestId() []byte {
	if x != nil {
		return x.ClientRequestId
	}
	return nil
}

func (x *AttestationChallengeResponseInner) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *AttestationChallengeResponseInner) GetChallengeSeed() []byte {
	if x != nil {
		return x.ChallengeSeed
	}
	return nil
}

func (x *AttestationChallengeResponseInner) GetPcrNonce() []byte {
	if x != nil {
		return x.PcrNonce
	}
	return nil
}

func (x *AttestationChallengeResponseInner) GetPcrSelectionBitfield() uint32 {
	if x != nil {
		return x.PcrSelectionBitfield
	}
	return 0
}

func (x *AttestationChallengeResponseInner) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type AttestWorkloadRequestInner struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Challenge       []byte                 `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Csr             []byte                 `protobuf:"bytes,2,opt,name=csr,proto3" json:"csr,omitempty"`
	WorkloadUnsName string                 `protobuf:"bytes,3,opt,name=workload_uns_name,json=workloadUnsName,proto3" json:"workload_uns_name,omitempty"`
	Evidence        *AttestationEvidence   `protobuf:"bytes,4,opt,name=evidence,proto3" json:"evidence,omitempty"`
	ClientRequestId []byte                 `protobuf:"bytes,5,opt,name=client_request_id,json=clientRequestId,proto3" json:"client_request_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AttestWorkloadRequestInner) Reset() {
	*x = AttestWorkloadRequestInner{}
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestWorkloadRequestInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestWorkloadRequestInner) ProtoMessage() {}

func (x *AttestWorkloadRequestInner) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestWorkloadRequestInner.ProtoReflect.Descriptor instead.
func (*AttestWorkloadRequestInner) Descriptor() ([]byte, []int) {
	return file_proto_hushmesh_workload_v1_workload_attestation_proto_rawDescGZIP(), []int{6}
}

func (x *AttestWorkloadRequestInner) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *AttestWorkloadRequestInner) GetCsr() []byte {
	if x != nil {
		return x.Csr
	}
	return nil
}

func (x *AttestWorkloadRequestInner) GetWorkloadUnsName() string {
	if x != nil {
		return x.WorkloadUnsName
	}
	return ""
}

func (x *AttestWorkloadRequestInner) GetEvidence() *AttestationEvidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *AttestWorkloadRequestInner) GetClientRequestId() []byte {
	if x != nil {
		return x.ClientRequestId
	}
	return nil
}

type AttestWorkloadResponseInner struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientRequestId []byte                 `protobuf:"bytes,1,opt,name=client_request_id,json=clientRequestId,proto3" json:"client_request_id,omitempty"`
	Svid            *X509SVID              `protobuf:"bytes,2,opt,name=svid,proto3" json:"svid,omitempty"`
	Bundle          *Bundle                `protobuf:"bytes,3,opt,name=bundle,proto3" json:"bundle,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AttestWorkloadResponseInner) Reset() {
	*x = AttestWorkloadResponseInner{}
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestWorkloadResponseInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestWorkloadResponseInner) ProtoMessage() {}

func (x *AttestWorkloadResponseInner) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestWorkloadResponseInner.ProtoReflect.Descriptor instead.
func (*AttestWorkloadResponseInner) Descriptor() ([]byte, []int) {
	return file_proto_hushmesh_workload_v1_workload_attestation_proto_rawDescGZIP(), []int{7}
}

func (x *AttestWorkloadResponseInner) GetClientRequestId() []byte {
	if x != nil {
		return x.ClientRequestId
	}
	return nil
}

func (x *AttestWorkloadResponseInner) GetSvid() *X509SVID {
	if x != nil {
		return x.Svid
	}
	return nil
}

func (x *AttestWorkloadResponseInner) GetBundle() *Bundle {
	if x != nil {
		return x.Bundle
	}
	return nil
}

type AttestationEvidence struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Quote            []byte                 `protobuf:"bytes,1,opt,name=quote,proto3" json:"quote,omitempty"`
	UserData         []byte                 `protobuf:"bytes,2,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	VarData          []byte                 `protobuf:"bytes,3,opt,name=var_data,json=varData,proto3" json:"var_data,omitempty"`
	VarDataOperation uint32                 `protobuf:"varint,4,opt,name=var_data_operation,json=varDataOperation,proto3" json:"var_data_operation,omitempty"`
	TpmQuote         *TpmQuoteEvidence      `protobuf:"bytes,5,opt,name=tpm_quote,json=tpmQuote,proto3" json:"tpm_quote,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AttestationEvidence) Reset() {
	*x = AttestationEvidence{}
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationEvidence) ProtoMessage() {}

func (x *AttestationEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationEvidence.ProtoReflect.Descriptor instead.
func (*AttestationEvidence) Descriptor() ([]byte, []int) {
	return file_proto_hushmesh_workload_v1_workload_attestation_proto_rawDescGZIP(), []int{8}
}

func (x *AttestationEvidence) GetQuote() []byte {
	if x != nil {
		return x.Quote
	}
	return nil
}

func (x *AttestationEvidence) GetUserData() []byte {
	if x != nil {
		return x.UserData
	}
	return nil
}

func (x *AttestationEvidence) GetVarData() []byte {
	if x != nil {
		return x.VarData
	}
	return nil
}

func (x *AttestationEvidence) GetVarDataOperation() uint32 {
	if x != nil {
		return x.VarDataOperation
	}
	return 0
}

func (x *AttestationEvidence) GetTpmQuote() *TpmQuoteEvidence {
	if x != nil {
		return x.TpmQuote
	}
	return nil
}

type TpmQuoteEvidence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        []byte                 `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	PcrValues     [][]byte               `protobuf:"bytes,3,rep,name=pcr_values,json=pcrValues,proto3" json:"pcr_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TpmQuoteEvidence) Reset() {
	*x = TpmQuoteEvidence{}
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TpmQuoteEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TpmQuoteEvidence) ProtoMessage() {}

func (x *TpmQuoteEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TpmQuoteEvidence.ProtoReflect.Descriptor instead.
func (*TpmQuoteEvidence) Descriptor() ([]byte, []int) {
	return file_proto_hushmesh_workload_v1_workload_attestation_proto_rawDescGZIP(), []int{9}
}

func (x *TpmQuoteEvidence) GetReport() []byte {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *TpmQuoteEvidence) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *TpmQuoteEvidence) GetPcrValues() [][]byte {
	if x != nil {
		return x.PcrValues
	}
	return nil
}

type SPIFFEID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrustDomain   string                 `protobuf:"bytes,1,opt,name=trust_domain,json=trustDomain,proto3" json:"trust_domain,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SPIFFEID) Reset() {
	*x = SPIFFEID{}
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SPIFFEID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPIFFEID) ProtoMessage() {}

func (x *SPIFFEID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPIFFEID.ProtoReflect.Descriptor instead.
func (*SPIFFEID) Descriptor() ([]byte, []int) {
	return file_proto_hushmesh_workload_v1_workload_attestation_proto_rawDescGZIP(), []int{10}
}

func (x *SPIFFEID) GetTrustDomain() string {
	if x != nil {
		return x.TrustDomain
	}
	return ""
}

func (x *SPIFFEID) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type X509SVID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertChain     [][]byte               `protobuf:"bytes,1,rep,name=cert_chain,json=certChain,proto3" json:"cert_chain,omitempty"`
	Id            *SPIFFEID              `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Hint          string                 `protobuf:"bytes,4,opt,name=hint,proto3" json:"hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *X509SVID) Reset() {
	*x = X509SVID{}
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *X509SVID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*X509SVID) ProtoMessage() {}

func (x *X509SVID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use X509SVID.ProtoReflect.Descriptor instead.
func (*X509SVID) Descriptor() ([]byte, []int) {
	return file_proto_hushmesh_workload_v1_workload_attestation_proto_rawDescGZIP(), []int{11}
}

func (x *X509SVID) GetCertChain() [][]byte {
	if x != nil {
		return x.CertChain
	}
	return nil
}

func (x *X509SVID) GetId() *SPIFFEID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *X509SVID) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *X509SVID) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

type X509Certificate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asn1          []byte                 `protobuf:"bytes,1,opt,name=asn1,proto3" json:"asn1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *X509Certificate) Reset() {
	*x = X509Certificate{}
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *X509Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*X509Certificate) ProtoMessage() {}

func (x *X509Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use X509Certificate.ProtoReflect.Descriptor instead.
func (*X509Certificate) Descriptor() ([]byte, []int) {
	return file_proto_hushmesh_workload_v1_workload_attestation_proto_rawDescGZIP(), []int{12}
}

func (x *X509Certificate) GetAsn1() []byte {
	if x != nil {
		return x.Asn1
	}
	return nil
}

type JWTKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JWTKey) Reset() {
	*x = JWTKey{}
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JWTKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTKey) ProtoMessage() {}

func (x *JWTKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTKey.ProtoReflect.Descriptor instead.
func (*JWTKey) Descriptor() ([]byte, []int) {
	return file_proto_hushmesh_workload_v1_workload_attestation_proto_rawDescGZIP(), []int{13}
}

func (x *JWTKey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *JWTKey) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *JWTKey) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type Bundle struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TrustDomain     string                 `protobuf:"bytes,1,opt,name=trust_domain,json=trustDomain,proto3" json:"trust_domain,omitempty"`
	X509Authorities []*X509Certificate     `protobuf:"bytes,2,rep,name=x509_authorities,json=x509Authorities,proto3" json:"x509_authorities,omitempty"`
	JwtAuthorities  []*JWTKey              `protobuf:"bytes,3,rep,name=jwt_authorities,json=jwtAuthorities,proto3" json:"jwt_authorities,omitempty"`
	RefreshHint     int64                  `protobuf:"varint,4,opt,name=refresh_hint,json=refreshHint,proto3" json:"refresh_hint,omitempty"`
	SequenceNumber  uint64                 `protobuf:"varint,5,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Bundle) Reset() {
	*x = Bundle{}
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bundle) ProtoMessage() {}

func (x *Bundle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bundle.ProtoReflect.Descriptor instead.
func (*Bundle) Descriptor() ([]byte, []int) {
	return file_proto_hushmesh_workload_v1_workload_attestation_proto_rawDescGZIP(), []int{14}
}

func (x *Bundle) GetTrustDomain() string {
	if x != nil {
		return x.TrustDomain
	}
	return ""
}

func (x *Bundle) GetX509Authorities() []*X509Certificate {
	if x != nil {
		return x.X509Authorities
	}
	return nil
}

func (x *Bundle) GetJwtAuthorities() []*JWTKey {
	if x != nil {
		return x.JwtAuthorities
	}
	return nil
}

func (x *Bundle) GetRefreshHint() int64 {
	if x != nil {
		return x.RefreshHint
	}
	return 0
}

func (x *Bundle) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

var File_proto_hushmesh_workload_v1_workload_attestation_proto protoreflect.FileDescriptor

const file_proto_hushmesh_workload_v1_workload_attestation_proto_rawDesc = "" +
	"\n" +
	"5proto/hushmesh/workload/v1/workload_attestation.proto\x12\x1fhushmesh.api.server.workload.v1\"\xd6\x01\n" +
	"\rSealedRequest\x12\x14\n" +
	"\x05suite\x18\x01 \x01(\rR\x05suite\x12(\n" +
	"\x10recipient_key_id\x18\x02 \x01(\fR\x0erecipientKeyId\x12)\n" +
	"\x10encapsulated_key\x18\x03 \x01(\fR\x0fencapsulatedKey\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x04 \x01(\fR\n" +
	"ciphertext\x12:\n" +
	"\x1asender_ecc_public_key_spki\x18\x05 \x01(\fR\x16senderEccPublicKeySpki\"F\n" +
	"\x0eSealedResponse\x12\x14\n" +
	"\x05suite\x18\x01 \x01(\rR\x05suite\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\fR\n" +
	"ciphertext\"\x17\n" +
	"\x15GetEnvelopeKeyRequest\"\x87\x02\n" +
	"\x16GetEnvelopeKeyResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\fR\x05keyId\x12-\n" +
	"\x13ecc_public_key_spki\x18\x02 \x01(\fR\x10eccPublicKeySpki\x12(\n" +
	"\x10mlkem_public_key\x18\x03 \x01(\fR\x0emlkemPublicKey\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\x12\x1d\n" +
	"\n" +
	"cert_chain\x18\x05 \x03(\fR\tcertChain\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\x12!\n" +
	"\ftrust_domain\x18\a \x01(\tR\vtrustDomain\"\xa4\x01\n" +
	" AttestationChallengeRequestInner\x12)\n" +
	"\x10attestation_type\x18\x01 \x01(\tR\x0fattestationType\x12*\n" +
	"\x11client_request_id\x18\x02 \x01(\fR\x0fclientRequestId\x12)\n" +
	"\x10client_timestamp\x18\x03 \x01(\x03R\x0fclientTimestamp\"\x86\x02\n" +
	"!AttestationChallengeResponseInner\x12*\n" +
	"\x11client_request_id\x18\x01 \x01(\fR\x0fclientRequestId\x12\x1c\n" +
	"\tchallenge\x18\x02 \x01(\fR\tchallenge\x12%\n" +
	"\x0echallenge_seed\x18\x03 \x01(\fR\rchallengeSeed\x12\x1b\n" +
	"\tpcr_nonce\x18\x04 \x01(\fR\bpcrNonce\x124\n" +
	"\x16pcr_selection_bitfield\x18\x05 \x01(\rR\x14pcrSelectionBitfield\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\"\xf6\x01\n" +
	"\x1aAttestWorkloadRequestInner\x12\x1c\n" +
	"\tchallenge\x18\x01 \x01(\fR\tchallenge\x12\x10\n" +
	"\x03csr\x18\x02 \x01(\fR\x03csr\x12*\n" +
	"\x11workload_uns_name\x18\x03 \x01(\tR\x0fworkloadUnsName\x12P\n" +
	"\bevidence\x18\x04 \x01(\v24.hushmesh.api.server.workload.v1.AttestationEvidenceR\bevidence\x12*\n" +
	"\x11client_request_id\x18\x05 \x01(\fR\x0fclientRequestId\"\xc9\x01\n" +
	"\x1bAttestWorkloadResponseInner\x12*\n" +
	"\x11client_request_id\x18\x01 \x01(\fR\x0fclientRequestId\x12=\n" +
	"\x04svid\x18\x02 \x01(\v2).hushmesh.api.server.workload.v1.X509SVIDR\x04svid\x12?\n" +
	"\x06bundle\x18\x03 \x01(\v2'.hushmesh.api.server.workload.v1.BundleR\x06bundle\"\xe1\x01\n" +
	"\x13AttestationEvidence\x12\x14\n" +
	"\x05quote\x18\x01 \x01(\fR\x05quote\x12\x1b\n" +
	"\tuser_data\x18\x02 \x01(\fR\buserData\x12\x19\n" +
	"\bvar_data\x18\x03 \x01(\fR\avarData\x12,\n" +
	"\x12var_data_operation\x18\x04 \x01(\rR\x10varDataOperation\x12N\n" +
	"\ttpm_quote\x18\x05 \x01(\v21.hushmesh.api.server.workload.v1.TpmQuoteEvidenceR\btpmQuote\"g\n" +
	"\x10TpmQuoteEvidence\x12\x16\n" +
	"\x06report\x18\x01 \x01(\fR\x06report\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x1d\n" +
	"\n" +
	"pcr_values\x18\x03 \x03(\fR\tpcrValues\"A\n" +
	"\bSPIFFEID\x12!\n" +
	"\ftrust_domain\x18\x01 \x01(\tR\vtrustDomain\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x97\x01\n" +
	"\bX509SVID\x12\x1d\n" +
	"\n" +
	"cert_chain\x18\x01 \x03(\fR\tcertChain\x129\n" +
	"\x02id\x18\x02 \x01(\v2).hushmesh.api.server.workload.v1.SPIFFEIDR\x02id\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12\x12\n" +
	"\x04hint\x18\x04 \x01(\tR\x04hint\"%\n" +
	"\x0fX509Certificate\x12\x12\n" +
	"\x04asn1\x18\x01 \x01(\fR\x04asn1\"]\n" +
	"\x06JWTKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\"\xa6\x02\n" +
	"\x06Bundle\x12!\n" +
	"\ftrust_domain\x18\x01 \x01(\tR\vtrustDomain\x12[\n" +
	"\x10x509_authorities\x18\x02 \x03(\v20.hushmesh.api.server.workload.v1.X509CertificateR\x0fx509Authorities\x12P\n" +
	"\x0fjwt_authorities\x18\x03 \x03(\v2'.hushmesh.api.server.workload.v1.JWTKeyR\x0ejwtAuthorities\x12!\n" +
	"\frefresh_hint\x18\x04 \x01(\x03R\vrefreshHint\x12'\n" +
	"\x0fsequence_number\x18\x05 \x01(\x04R\x0esequenceNumber2\x88\x03\n" +
	"\x13WorkloadAttestation\x12\x81\x01\n" +
	"\x0eGetEnvelopeKey\x126.hushmesh.api.server.workload.v1.GetEnvelopeKeyRequest\x1a7.hushmesh.api.server.workload.v1.GetEnvelopeKeyResponse\x12z\n" +
	"\x17GetAttestationChallenge\x12..hushmesh.api.server.workload.v1.SealedRequest\x1a/.hushmesh.api.server.workload.v1.SealedResponse\x12q\n" +
	"\x0eAttestWorkload\x12..hushmesh.api.server.workload.v1.SealedRequest\x1a/.hushmesh.api.server.workload.v1.SealedResponseB;Z9github.com/spiffe/go-spiffe/v2/proto/hushmesh/workload/v1b\x06proto3"

var (
	file_proto_hushmesh_workload_v1_workload_attestation_proto_rawDescOnce sync.Once
	file_proto_hushmesh_workload_v1_workload_attestation_proto_rawDescData []byte
)

func file_proto_hushmesh_workload_v1_workload_attestation_proto_rawDescGZIP() []byte {
	file_proto_hushmesh_workload_v1_workload_attestation_proto_rawDescOnce.Do(func() {
		file_proto_hushmesh_workload_v1_workload_attestation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hushmesh_workload_v1_workload_attestation_proto_rawDesc), len(file_proto_hushmesh_workload_v1_workload_attestation_proto_rawDesc)))
	})
	return file_proto_hushmesh_workload_v1_workload_attestation_proto_rawDescData
}

var file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_hushmesh_workload_v1_workload_attestation_proto_goTypes = []any{
	(*SealedRequest)(nil),                     // 0: hushmesh.api.server.workload.v1.SealedRequest
	(*SealedResponse)(nil),                    // 1: hushmesh.api.server.workload.v1.SealedResponse
	(*GetEnvelopeKeyRequest)(nil),             // 2: hushmesh.api.server.workload.v1.GetEnvelopeKeyRequest
	(*GetEnvelopeKeyResponse)(nil),            // 3: hushmesh.api.server.workload.v1.GetEnvelopeKeyResponse
	(*AttestationChallengeRequestInner)(nil),  // 4: hushmesh.api.server.workload.v1.AttestationChallengeRequestInner
	(*AttestationChallengeResponseInner)(nil), // 5: hushmesh.api.server.workload.v1.AttestationChallengeResponseInner
	(*AttestWorkloadRequestInner)(nil),        // 6: hushmesh.api.server.workload.v1.AttestWorkloadRequestInner
	(*AttestWorkloadResponseInner)(nil),       // 7: hushmesh.api.server.workload.v1.AttestWorkloadResponseInner
	(*AttestationEvidence)(nil),               // 8: hushmesh.api.server.workload.v1.AttestationEvidence
	(*TpmQuoteEvidence)(nil),                  // 9: hushmesh.api.server.workload.v1.TpmQuoteEvidence
	(*SPIFFEID)(nil),                          // 10: hushmesh.api.server.workload.v1.SPIFFEID
	(*X509SVID)(nil),                          // 11: hushmesh.api.server.workload.v1.X509SVID
	(*X509Certificate)(nil),                   // 12: hushmesh.api.server.workload.v1.X509Certificate
	(*JWTKey)(nil),                            // 13: hushmesh.api.server.workload.v1.JWTKey
	(*Bundle)(nil),                            // 14: hushmesh.api.server.workload.v1.Bundle
}
var file_proto_hushmesh_workload_v1_workload_attestation_proto_depIdxs = []int32{
	8,  // 0: hushmesh.api.server.workload.v1.AttestWorkloadRequestInner.evidence:type_name -> hushmesh.api.server.workload.v1.AttestationEvidence
	11, // 1: hushmesh.api.server.workload.v1.AttestWorkloadResponseInner.svid:type_name -> hushmesh.api.server.workload.v1.X509SVID
	14, // 2: hushmesh.api.server.workload.v1.AttestWorkloadResponseInner.bundle:type_name -> hushmesh.api.server.workload.v1.Bundle
	9,  // 3: hushmesh.api.server.workload.v1.AttestationEvidence.tpm_quote:type_name -> hushmesh.api.server.workload.v1.TpmQuoteEvidence
	10, // 4: hushmesh.api.server.workload.v1.X509SVID.id:type_name -> hushmesh.api.server.workload.v1.SPIFFEID
	12, // 5: hushmesh.api.server.workload.v1.Bundle.x509_authorities:type_name -> hushmesh.api.server.workload.v1.X509Certificate
	13, // 6: hushmesh.api.server.workload.v1.Bundle.jwt_authorities:type_name -> hushmesh.api.server.workload.v1.JWTKey
	2,  // 7: hushmesh.api.server.workload.v1.WorkloadAttestation.GetEnvelopeKey:input_type -> hushmesh.api.server.workload.v1.GetEnvelopeKeyRequest
	0,  // 8: hushmesh.api.server.workload.v1.WorkloadAttestation.GetAttestationChallenge:input_type -> hushmesh.api.server.workload.v1.SealedRequest
	0,  // 9: hushmesh.api.server.workload.v1.WorkloadAttestation.AttestWorkload:input_type -> hushmesh.api.server.workload.v1.SealedRequest
	3,  // 10: hushmesh.api.server.workload.v1.WorkloadAttestation.GetEnvelopeKey:output_type -> hushmesh.api.server.workload.v1.GetEnvelopeKeyResponse
	1,  // 11: hushmesh.api.server.workload.v1.WorkloadAttestation.GetAttestationChallenge:output_type -> hushmesh.api.server.workload.v1.SealedResponse
	1,  // 12: hushmesh.api.server.workload.v1.WorkloadAttestation.AttestWorkload:output_type -> hushmesh.api.server.workload.v1.SealedResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_hushmesh_workload_v1_workload_attestation_proto_init() }
func file_proto_hushmesh_workload_v1_workload_attestation_proto_init() {
	if File_proto_hushmesh_workload_v1_workload_attestation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hushmesh_workload_v1_workload_attestation_proto_rawDesc), len(file_proto_hushmesh_workload_v1_workload_attestation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hushmesh_workload_v1_workload_attestation_proto_goTypes,
		DependencyIndexes: file_proto_hushmesh_workload_v1_workload_attestation_proto_depIdxs,
		MessageInfos:      file_proto_hushmesh_workload_v1_workload_attestation_proto_msgTypes,
	}.Build()
	File_proto_hushmesh_workload_v1_workload_attestation_proto = out.File
	file_proto_hushmesh_workload_v1_workload_attestation_proto_goTypes = nil
	file_proto_hushmesh_workload_v1_workload_attestation_proto_depIdxs = nil
}
